# Generated by Django 4.0.3 on 2022-03-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='a', max_length=13, verbose_name='ISBN'),
            preserve_default=False,
        ),
    ]
